// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcrash

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWithPtr_Mock creates a new instance of WithPtr_Mock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithPtr_Mock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithPtr_Mock {
	mock := &WithPtr_Mock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WithPtr_Mock is an autogenerated mock type for the WithPtr type
type WithPtr_Mock struct {
	mock.Mock
}

type WithPtr_Mock_Expecter struct {
	mock *mock.Mock
}

func (_m *WithPtr_Mock) EXPECT() *WithPtr_Mock_Expecter {
	return &WithPtr_Mock_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type WithPtr_Mock
func (_mock *WithPtr_Mock) Do(value *Value) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Value) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WithPtr_Mock_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type WithPtr_Mock_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - value *Value
func (_e *WithPtr_Mock_Expecter) Do(value interface{}) *WithPtr_Mock_Do_Call {
	return &WithPtr_Mock_Do_Call{Call: _e.mock.On("Do", value)}
}

func (_c *WithPtr_Mock_Do_Call) Run(run func(value *Value)) *WithPtr_Mock_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Value
		if args[0] != nil {
			arg0 = args[0].(*Value)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WithPtr_Mock_Do_Call) Return(err error) *WithPtr_Mock_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WithPtr_Mock_Do_Call) RunAndReturn(run func(value *Value) error) *WithPtr_Mock_Do_Call {
	_c.Call.Return(run)
	return _c
}
